### ISSUE TITLE
MVP for Examples

### ISSUE THREAD

**Issue by tcr3dr** [3drobotics/solodevguide#18]
- [ ] [Create a smartshot](https://github.com/3drobotics/solodevguide/issues/15)
- [ ] [Create an onboard video consumer](https://github.com/3drobotics/solodevguide/issues/19)
- [ ] [Create an onboard video output](https://github.com/3drobotics/solodevguide/issues/9)
- [x] [Communicate with an App from an onboard server](https://github.com/3drobotics/solodevguide/issues/14)
